spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sugang  # MySQL ?????? URL
    username: root                       # ?????? ??? ??
    password: yaejin02                       # ?????? ????
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ???? ???
    hikari:
      maximum-pool-size: 10                    # ?? ??? ? ?? (??? ?? ??)
  jpa:
    hibernate:
      ddl-auto: update                          # Hibernate DDL ?? ?? ?? (?: update, create, none)
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL ?? ??

jwt:
  secret: c3VwZXItc2VjcmV0LWp3dC1rZXktMjAyNS1mb3Itc3VnYW5n
